version: '3.8'

services:
  spotistate:
    image: ghcr.io/dpozinen/spotistate:latest
    container_name: spotistate
    ports:
      - "${APP_PORT:-80}:80"
      - "${API_PORT:-8080}:8080"

    volumes:
      - spotistate_logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - spotistate-network

  postgres:
    image: postgres:15-alpine
    container_name: spotistate-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-spotistate}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spotistate-network

volumes:
  postgres_data:
    driver: local
  spotistate_logs:
    driver: local

networks:
  spotistate-network:
    driver: bridge
